name: DangerJS Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - '*'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  statuses: write


jobs:
  pull-request-style-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run DangerJS
      uses: tomassebestik/reusable-danger@master  # replace with your repo details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
